"""add boards table

Revision ID: 25808c7a7deb
Revises: 00cf8c105d85
Create Date: 2023-08-28 09:26:47.418176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25808c7a7deb'
down_revision = '00cf8c105d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colnums', sa.String(), nullable=True),
    sa.Column('rownums', sa.String(), nullable=True),
    sa.Column('game_cnt', sa.Integer(), nullable=True),
    sa.Column('empty_squares', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boards')
    # ### end Alembic commands ###
